import bini from '../public/bini.jpg'
import outlier from '../public/outlier.jpg'
import invisibleTech from '../public/invisibleTech.png'

export const experienceData = [
    {
       position: "Advanced AI Data Trainer",
        company: "Invisible Technologies",
        startDate: "January 2024",
        endDate: "Present",
        responsibilities: "Worked on multiple projects on preparing training data for AI model performance enhancement, including evaluating code generated by AI in languages like JavaScript, Python, TypeScript, HTML/CSS.",
        companyLogo: invisibleTech
    },
    {
       position: "Software Engineer for AI Data Training",
        company: "Outlier",
        startDate: "November 2024",
        endDate: "April 2024",
        responsibilities: "Prepared and reviewed training data for LLMs in JavaScript and Python on different projects, including code generation, code debugging, code review, code documentation, UI enhancement, etc.",
        companyLogo: outlier
    },
    {
        position: "Software Engineer",
        company: "Bini",
        startDate: "September 2024",
        endDate: "October 2024",
        responsibilities: "Full-Stack Engineer with Frontend focus. Tech stack - React, Typescript, Next.js, Tanstack Query, ShadCN, Material UI.",
        companyLogo: bini
    }
]